name: Build Mermaid

on:
  push:
    paths:
      - 'docs/workflow.mmd'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate diagram from Mermaid file
        uses: jp3492/mermaid-cli-action@v1
        with:
          files: |
            docs/workflow.mmd
          output: |
            docs/workflow.svg
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update workflow diagram"
          file_pattern: docs/workflow.svg
